# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [2]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
# np.savetxt('data.txt', data)    # 공백으로 구분
np.savetxt('data.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('data.txt', delimiter=",")
print(load_data)

[[0.06012044 0.43990368 0.67967888]
 [0.91258305 0.17890126 0.52437289]
 [0.82297339 0.75831521 0.61509718]
 [0.47684917 0.85149964 0.6094466 ]
 [0.5423006  0.16215351 0.20130069]]
[[0.06012044 0.43990368 0.67967888]
 [0.91258305 0.17890126 0.52437289]
 [0.82297339 0.75831521 0.61509718]
 [0.47684917 0.85149964 0.6094466 ]
 [0.5423006  0.16215351 0.20130069]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [4]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
if not os.path.exists('./generated'):
    os.makedirs('./generated')
np.save('./generated/data', data)

load_data = np.load('./generated/data.npy')
print("load_data :\n", load_data)

data :
 [[0.79317409 0.42566764 0.47612377]
 [0.61480447 0.83905847 0.93153507]
 [0.78807868 0.1112432  0.60603854]
 [0.04851103 0.28883255 0.25997041]
 [0.50656938 0.71186769 0.92648998]]
load_data :
 [[0.79317409 0.42566764 0.47612377]
 [0.61480447 0.83905847 0.93153507]
 [0.78807868 0.1112432  0.60603854]
 [0.04851103 0.28883255 0.25997041]
 [0.50656938 0.71186769 0.92648998]]
